import Mathlib

open scoped BigOperators
open Function

/-!
# Sup-norm density of finite-separable functions on the k-simplex

The Maynard/GPY variational problem `M_k = sup_F (∑_i J_i F)/I(F)` over smooth test
functions `F` supported on the simplex `R_k = {t : 0 ≤ t_i, ∑ t_i ≤ 1}` is realised by
*finite-separable* `F` (finite sums of products of 1-D functions, `F t = ∑_j c_j ∏_i Fs_{j,i}(t_i)`).
The analytic crux, isolated after the ratio-continuity is discharged separately, is the
following **pure approximation-theory** density statement (NO number theory):

  any smooth `F` supported on the simplex can be approximated, uniformly on the simplex
  to within any `δ > 0`, by a finite-separable smooth function `G` that is itself
  supported on the simplex.

## Strategy (box-tiling tensor bumps)
`closure(support F)` is compact and contained in the simplex. Cover it by finitely many
small open boxes (products of intervals) whose closures lie inside the simplex (possible
since each box has side `< 1/k` so its sup-coordinate-sum is `< 1`). Take a smooth partition
of unity subordinate to a slightly larger tensor-bump cover: each bump is a *product* of
1-D `ContDiffBump`s (hence separable), supported in its box (hence in the simplex). Write
`G = ∑_boxes (value of F at box centre) · (tensor bump)`; this is finite-separable, smooth,
supported in the simplex, and within `δ` of `F` uniformly by uniform continuity of `F` on
the compact simplex (mesh chosen from `δ` via `Metric.uniformContinuousOn_of_continuous`).

Alternatively use Stone–Weierstrass density of the subalgebra generated by coordinate
functions in `C(simplex)`, then multiply the polynomial approximant by a separable smooth
bump equal to `1` on `support F` to restore `support ⊆ simplex`.

Keep `#print axioms` clean (no `sorry`).
-/

namespace AristotleSepDense

/-- The standard `k`-simplex `{t : ∀ i, 0 ≤ t i ∧ ∑ i, t i ≤ 1}`. -/
def simplex (k : ℕ) : Set (Fin k → ℝ) := { t | (∀ i, 0 ≤ t i) ∧ ∑ i, t i ≤ 1 }

/-- `F` is finite-separable: a finite sum of products of 1-D functions. -/
def IsFiniteSeparable {k : ℕ} (F : (Fin k → ℝ) → ℝ) : Prop :=
  ∃ (J : ℕ) (c : Fin J → ℝ) (Fs : Fin J → Fin k → ℝ → ℝ),
    ∀ t : Fin k → ℝ, F t = ∑ j : Fin J, c j * ∏ i : Fin k, Fs j i (t i)

theorem separable_dense_sup (k : ℕ) (F : (Fin k → ℝ) → ℝ)
    (hF : ContDiff ℝ ⊤ F) (hsupp : Function.support F ⊆ simplex k)
    (δ : ℝ) (hδ : 0 < δ) :
    ∃ G : (Fin k → ℝ) → ℝ,
      IsFiniteSeparable G ∧ ContDiff ℝ ⊤ G ∧ Function.support G ⊆ simplex k ∧
      (∀ t ∈ simplex k, |F t - G t| ≤ δ) := by
  sorry

end AristotleSepDense
