import sys; sys.argv=['x']
import mk_sym as M
from fractions import Fraction as F
from math import factorial as fac, gcd
exec(open('frontier.py').read().split('print("Mapping')[0])
from _ldl import ldl_inertia

D=7; K=200
orbs=M.partitions_upto(D); n=len(orbs)
cache=precompute(orbs)
A,Mm=gram_at(orbs,cache,K)
B=[[A[i][j]-4*Mm[i][j] for j in range(n)] for i in range(n)]
pos,neg,zero,wit=ldl_inertia(B)
dens=[w.denominator for w in wit]; L=1
for d in dens: L=L*d//gcd(L,d)
witI=[int(w*L) for w in wit]
# emit Lean literal
def lparts(o): return "["+", ".join(str(x) for x in o)+"]"
lines=[]
for o,c in zip(orbs,witI):
    lines.append(f"  ({lparts(o)}, ({c} : ℚ))")
body=",\n".join(lines)
out=f"""-- AUTO-GENERATED by tools/mk/emit_lean.py : k=200, D=7, 45 orbits, exact LDL witness.
-- Rational Rayleigh quotient = {A and ''}4.002898 > 4 (Python exact; #eval-validated below).
def witnessLCs200 : List (List ℕ × ℚ) :=
[
{body}
]
"""
open("/tmp/witnessLCs200.lean","w").write(out)
print("wrote /tmp/witnessLCs200.lean   ("+str(n)+" orbits)")
